services:
  database:
    ports:
      - 5432:5432
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: postgres

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 3000:3000
    volumes:
      - .:/app/
    command: air