services:
  database:
    ports:
      - 6379:6379
    image: bitnami/redis
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - redis/data:/bitnami/redis/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 3000:3000
    volumes:
      - .:/app/
    command: air