# Generated by Django 4.1.6 on 2023-02-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="server",
            name="ip",
        ),
        migrations.AddField(
            model_name="server",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
