# Generated by Django 4.1.6 on 2023-02-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_server_ip_server_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="torrent",
            name="magnet",
            field=models.TextField(blank=True, null=True),
        ),
    ]
