# Generated by Django 4.1.7 on 2023-02-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_torrent_magnet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Key",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("private_key", models.CharField(blank=True, max_length=64, null=True)),
                ("public_key", models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
