# Generated by Django 4.2.4 on 2023-08-05 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="server",
            old_name="public_key",
            new_name="key",
        ),
    ]
